config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  resources :orders

  resources :categories do
    resources :products, only: [:index, :new, :create]
  end
  resources :products, only: [:show, :edit, :update, :destroy]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'pages/index' => 'pages#index'
  get 'products' => 'products#index'
  
end

app/views/pages/_product_row.html.erb
<div class="product col-xs-6 col-sm-6 col-md-4 product_collection item3_1 item2_1">
				<div class="product_wrapper">
					<div class="product_img">
						<div class="img_change"> 
								<span class="img_change_wrapper">
									<!-- Підтягнути фотки з бази -->
									<%= link_to image_tag(product.image), product_path(product), {alt: 'Carter Cocktail Shaker'} %>
									<%= link_to image_tag(product.image_2), product_path(product), {alt: 'Carter Cocktail Shaker', class: 'img__2', style: 'opacity: 0;'} %>
								</span> 
								<span class="product_badge new">New</span>
						</div>
					
					</div>
					<div class="product_info">
						<div class="product_price">
							<span class="money"><%= number_to_currency(product.price) %></span>
						</div>
						<div class="product_name">
							<%= link_to product.name, product_path(product), title: "Carter Cocktail Shaker" %>
							
						</div>
						<div class="product_desc product_desc__short">
							<%= truncate(product.description, length: 60) %>
						
						</div>
						
						<div class="product_links">
							<!-- СТВОРИТИ ФОРМУ НА КНОПКУ КОРЗИНИ !!!!!!! -->
							<%= form_for order_item, remote: true do |f| %>
                <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
                 <div class="input-group">
                  <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, style: 'width: 60px' %>
                 <div class="input-group-btn">
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "Add to Cart", class: "btn btn-primary" %>
              </div>
                </div>
              <% end %>
             
      
						
						</div>
					</div>
				</div>
			</div>

app/views/pages/index.html.erb
<div class="main_content  col-sm-9 col-sm-push-3">
	
	<!--Slider start-->
		<div class="swiper-container swiper-container-horizontal swiper-container-fade" id="swiper">
			<div class="swiper-wrapper" style="transition-duration: 0ms;">
				<div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="2" style="width: 870px; transform: translate3d(0px, 0px, 0px); opacity: 1; transition-duration: 0ms;">
					<div id="swiper_1"></div>
					<%#= image_tag("/assets/slide3_image.jpg", alt: "")%>
				
					<div class="slider_caption">
						<h2>New Cooking Essentials</h2>
						<p>Your source for professional-quality cookware. Shop for kitchen appliances, cooking essentials from the comfort of your home. See the latest deals on selected products.</p><a class="btn" href="https://theme262-cookware.myshopify.com/collections/cooking-utensils">Shop now!</a>
					</div>
				</div>
				<div class="swiper-slide swiper-slide-prev" data-swiper-slide-index="0" style="width: 870px; transform: translate3d(-870px, 0px, 0px); opacity: 1; transition-duration: 0ms;">
					<div id="swiper_2"></div>
		
					<%#= image_tag("/assets/slide1_image.jpg", alt: "")%>
				
					<div class="slider_caption">
						<h2>Stainless Steel Cookware Set</h2>
						<p>Your source for professional-quality cookware. Shop for kitchen appliances, cooking essentials from the comfort of your home. See the latest deals on selected products.</p><a class="btn" href="https://theme262-cookware.myshopify.com/collections/bakeware">Shop now!</a>
					</div>
				</div>
				<div class="swiper-slide swiper-slide-active" data-swiper-slide-index="1" style="width: 870px; transform: translate3d(-1740px, 0px, 0px); opacity: 1; transition-duration: 0ms;">
					<div id="swiper_3"></div>
					<%#= image_tag("/assets/slide2_image.jpg", alt: "")%>
					
					<div class="slider_caption">
						<h2>Must-haves for any cook</h2>
						<p>Your source for professional-quality cookware. Shop for kitchen appliances, cooking essentials from the comfort of your home. See the latest deals on selected products.</p><a class="btn" href="https://theme262-cookware.myshopify.com/collections/cookware-sets">Shop now!</a>
					</div>
				</div>
				<div class="swiper-slide swiper-slide-next" data-swiper-slide-index="2" style="width: 870px; transform: translate3d(-2610px, 0px, 0px); opacity: 0; transition-duration: 0ms;">
					<div id="swiper_4"></div>
					<%#= image_tag("/assets/slide3_image.jpg", alt: "")%>
					
					<div class="slider_caption">
						<h2>New Cooking Essentials</h2>
						<p>Your source for professional-quality cookware. Shop for kitchen appliances, cooking essentials from the comfort of your home. See the latest deals on selected products.</p><a class="btn" href="https://theme262-cookware.myshopify.com/collections/cooking-utensils">Shop now!</a>
					</div>
				</div>
				<div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="0" style="width: 870px; transform: translate3d(-3480px, 0px, 0px); opacity: 0; transition-duration: 0ms;">
					<div id="swiper_5"></div>
					<!--<img alt="" src="/assets/slide1_image.jpg">-->
					<div class="slider_caption">
						<h2>Stainless Steel Cookware Set</h2>
						<p>Your source for professional-quality cookware. Shop for kitchen appliances, cooking essentials from the comfort of your home. See the latest deals on selected products.</p><a class="btn" href="https://theme262-cookware.myshopify.com/collections/bakeware">Shop now!</a>
					</div>
				</div>
			</div>
			<div class="swiper_btn" id="swiper_btn_prev"></div>
			<div class="swiper_btn" id="swiper_btn_next"></div>
		</div>
	<!--Slider end-->
	
	<h3 class="text-center">Products for Sale</h3>
<div id="collection_sorted" style="opacity: 1;">
		<div class="product_listing_main">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

	
	
</div>

<div class="sidebar col-sm-3 sidebar_left col-sm-pull-9">
   <%= render '/shared/navleft' %>
</div>
		
		
		

		

	