config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  resources :orders

  resources :categories do
    resources :products, only: [:index, :new, :create]
  end
  resources :products, only: [:show, :edit, :update, :destroy]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'pages/index' => 'pages#index'
  get 'products' => 'products#index'
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]
  
  # before_filter do 
  #   redirect_to :new_user_session_path unless current_user && current_user.admin?
  # end
  # GET /products
  # GET /products.json
  def index
    @cat = Category.first(5)
    @category = Category.find(params[:category_id])
    @products = @category.products
    @order_item = current_order.order_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def authenticate_admin!
    # check if current user is admin
    unless current_user.admin
      # if current_user is not admin redirect to some route
      redirect_to new_user_session_path
    end
    # if current_user is admin he will proceed to edit action
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :cost, :qty, :weight, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.label :qty %>
    <%= f.number_field :qty %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="main_content col-sm-9 col-sm-push-3">
		<p id="notice"><%= notice %></p>
		<h1>Products</h1>
		<% if current_user.try(:admin?) %>
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Price</th>
					<th>Description</th>
					<th>Cost</th>
					<th>Qty</th>
					<th>Weight</th>
					<th>Image</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<%@products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td><%= product.price %></td>
					<td><%= truncate(product.description, length: 30) %></td>
					<td><%= product.cost %></td>
					<td><%= product.qty %></td>
					<td><%= product.weight %></td>
					<td><%= product.image %></td>
					<td><%= link_to 'Show', product %></td>
					<td><%= link_to 'Edit', edit_product_path(product) %></td>
					<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr><%end %>
			</tbody>
		</table><br>
		<%= link_to 'New Product', new_category_path %>
		<% end %>
		<h1 class="page_heading">Cookware</h1>
		<ul class="tags clearfix">
			<li class="active">
				<a href="/collections/cookware">All</a>
			</li>
			<li>
				<a href="/collections/cookware/candy-making-supplies" title="Show products matching tag Candy Making Supplies">Candy Making Supplies</a>
			</li>
			<li>
				<a href="/collections/cookware/commercial-cookware" title="Show products matching tag Commercial Cookware">Commercial Cookware</a>
			</li>
			<li>
				<a href="/collections/cookware/organizational-supplies" title="Show products matching tag Organizational Supplies">Organizational Supplies</a>
			</li>
			<li>
				<a href="/collections/cookware/professional-cutlery" title="Show products matching tag Professional Cutlery">Professional Cutlery</a>
			</li>
		</ul><!-- collection image & description -->
		<div class="row collection_info">
			<div class="col-sm-3 collection_img"><img alt="Cookware" src="//cdn.shopify.com/s/files/1/1398/6279/collections/carter_cocktail_shaker_1_medium.png?v=1469534060"></div>
			<div class="col-sm-9 collection_desc">
				<div class="rte">
					There is a common opinion that customer care service makes 90% of your reputation and we believe this to be a business truth. That’s why we are proud to inform you that you can always rely on our wonderful support system that is available 24/7. Every business is very demanding but the secret of success lies between the right choice of the business strategy and reliable suppliers.Those were the times when people still preferred to buy products at brick-and-mortar stores instead of buying online. Nevertheless we’ve decided to create an online shop and we are so glad to welcome you here. Kitchen Supplies store was founded by several enthusiasts in 2002.Taking care of our clients was and still is a main aim of our company and it will stay the same till the end of days.
				</div>
			</div>
		</div><!-- products sorting -->
		<div class="loader_off" id="product_listing_preloader">
			<div class="global_loader"></div>
		</div>
		<div id="collection_sorted" style="opacity: 1;">
			<div class="product_listing_main">
				<% @products.each do |product| %>
					<%= render "/pages/product_row", product: product, order_item: @order_item %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="sidebar col-sm-3 sidebar_left col-sm-pull-9">
		<%= render '/shared/navleft' %>
	</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @product.qty %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>