config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  resources :orders

  resources :categories do
    resources :products, only: [:index, :new, :create]
  end
  resources :products, only: [:show, :edit, :update, :destroy]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'pages/index' => 'pages#index'
  get 'products' => 'products#index'
  
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cook | Cook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link media="all" type="text/css" rel="stylesheet" href="//cdn.materialdesignicons.com/1.8.36/css/materialdesignicons.min.css"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"  rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.jquery.js"></script>
  </head>

  <body class="template-collection scheme_1 subpage" id="cookware">
<div style="display: block;" class="on" id="page_preloader"><div class="global_loader"></div></div>

<!-- HEADER -->
<header>
<div class="container">
	<div class="flexbox">
		<!-- LOGO -->
		<div id="logo" class="logo_main">
			<%= link_to root_path do %>
				<div class="logo_bg"></div>
			<% end %>
		</div>
		<!-- HEADER SEARCH -->
		<div class="header_search">
			<form action="/search" method="get" class="search_form">
				<i class="material-icons">search</i>
				<input value="Search store" id="search-field" name="q" placeholder="Search store" class="hint" type="text">
				<button id="search-submit" type="submit" class="btn">Search</button>
			</form>
		</div>

		<div class="header_right">
			<!-- USER MENU -->
			<ul class="header_user">
				<li>
					<%= link_to 'Checkout', new_order_path%>
				</li>
							<!-- <li class="wishlist"><a href="/pages/wishlist">Wishlist</a></li> -->
				<li class="checkout">
					<% if user_signed_in? %>
						<%= link_to "Logout", destroy_user_session_path, :method => :delete %>
					<% else %>
						<%= link_to "Login", new_user_session_path %>
					<% end %>
				</li>
			</ul>
		
		<% if current_user.try(:admin?) %>
		 <span style="color: red; font-weight: bold;">Hello, Admin!</span>
		<% end %>
			
			<!-- HEADER CUSTOM BLOCK -->
			<div class="header_custom">
				  <i class="material-icons">phone</i>
					<a href="callto:800-2345-6789">800-2345-6789</a>
			</div>
			
		</div>
	</div>
</div>
</header>

   <div id="main" role="main">
		<div class="container">
			<div class="row">
				<%= render '/shared/navtop', object: @category %>
				<p id="notice" style="color:green; font-weight: bold; float:right"><%= notice %></p>
			     
			     <%= yield %>
			 
			 </div>
		</div>
	</div>
	<%= render 'shared/footer' %>
</body>
</html>